server:
  port: 9000
spring:
  application:
    name: orleans
bootstrap:
  servers: localhost:9092
app:
  user: admin
  password: admin
  roles: USER
  environment: dev
multipart:
  enabled: true
  maxFileSize: 10Mb
  maxRequestSize: 10Mb
max:
  request:
    size: 100000