server:
  port: 9000
spring:
  application:
    name: orleans
app:
  user: admin
  password: admin
  roles: USER
  environment: dev
multipart:
  enabled: true
  maxFileSize: 10Mb
  maxRequestSize: 10Mb
bootstrap:
  servers: dimw-kafkabroker101.echostar.com:9092
max:
  request:
    size: 100000